[package]
name = "oszilloskop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
cpal = "0.15.3"
spmcq = "0.1.0"
